# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issued',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='received',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
