# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190122_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
