# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-23 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190123_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cetagory',
            new_name='requisition',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='whom',
        ),
    ]
